basePath: /api/v1
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:4321
info:
  contact: {}
  description: 这是chatbox api swagger文档.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ChatBox API
  version: "0.01"
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: 使用邮箱密码注册
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 用户注册
      tags:
      - Auth
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
